import React from "react";
import { useNavigate } from "react-router";
import { reports } from "../../lib/data";
import { ChevronLeft, Share2, AlertCircle, CheckCircle, Info } from "lucide-react";
import { motion } from "motion/react";

export default function AISummary() {
  const navigate = useNavigate();
  const report = reports[0]; // Using the first report as the "new" one

  return (
    <div className="bg-slate-50 dark:bg-slate-900 min-h-screen pb-24">
      <div className="max-w-4xl mx-auto">
      <header className="bg-white dark:bg-slate-800 px-6 pt-12 pb-4 shadow-sm flex items-center justify-between sticky top-0 z-20 md:pt-8 md:rounded-b-2xl transition-colors">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate("/records")} className="p-2 -ml-2 rounded-full hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-600 dark:text-slate-300 transition-colors">
             <ChevronLeft size={24} />
          </button>
          <h1 className="text-lg font-bold text-slate-900 dark:text-white">AI Summary</h1>
        </div>
        <button className="text-blue-600 dark:text-blue-400 font-medium text-sm">Edit</button>
      </header>

      <div className="p-6 space-y-6">
        
        {/* Header Card */}
        <div className="bg-white dark:bg-slate-800 p-5 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 transition-colors">
           <div className="flex justify-between items-start mb-4">
              <div>
                 <h2 className="text-xl font-bold text-slate-900 dark:text-white">{report.title}</h2>
                 <p className="text-sm text-slate-500 dark:text-slate-400">{report.labName} • {report.date}</p>
              </div>
              <div className="w-10 h-10 rounded-full bg-blue-50 dark:bg-blue-900/20 flex items-center justify-center text-blue-600 dark:text-blue-400">
                 <Share2 size={18} />
              </div>
           </div>
           
           <div className="bg-slate-50 dark:bg-slate-700/50 p-4 rounded-xl border border-slate-100 dark:border-slate-700 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
              <span className="font-bold text-blue-600 dark:text-blue-400 block mb-1">AI Insight:</span>
              {report.summary}
           </div>
        </div>

        {/* Parameters List */}
        <div className="space-y-3">
           <h3 className="font-bold text-slate-900 dark:text-white px-1">Biomarkers Detected</h3>
           
           {report.parameters.map((param, idx) => (
             <motion.div 
               key={idx}
               initial={{ opacity: 0, y: 10 }}
               animate={{ opacity: 1, y: 0 }}
               transition={{ delay: idx * 0.1 }}
               className="bg-white dark:bg-slate-800 p-4 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 flex items-center justify-between transition-colors"
             >
                <div className="flex-1">
                   <p className="font-semibold text-slate-900 dark:text-white">{param.name}</p>
                   <p className="text-xs text-slate-400">Range: {param.range} {param.unit}</p>
                </div>
                
                <div className="text-right">
                   <p className={`font-bold text-lg ${
                      param.status === "Low" ? "text-amber-500" :
                      param.status === "High" ? "text-red-500" : "text-slate-900 dark:text-white"
                   }`}>
                      {param.value} <span className="text-xs text-slate-400 font-normal">{param.unit}</span>
                   </p>
                   
                   {param.status !== "Normal" && (
                     <div className={`text-[10px] font-bold uppercase tracking-wider flex items-center justify-end gap-1 mt-0.5 ${
                        param.status === "Low" ? "text-amber-500" : "text-red-500"
                     }`}>
                        {param.status === "Low" ? "Below Range" : "Above Range"}
                        <AlertCircle size={10} />
                     </div>
                   )}
                </div>
             </motion.div>
           ))}
        </div>

        {/* Disclaimer */}
        <div className="flex gap-3 bg-blue-50 dark:bg-blue-900/10 p-4 rounded-xl border border-blue-100 dark:border-blue-900/30 items-start">
           <Info className="text-blue-600 dark:text-blue-400 shrink-0 mt-0.5" size={18} />
           <p className="text-xs text-blue-800 dark:text-blue-200 leading-relaxed">
              This summary is generated by AI and should not be considered medical advice. Always consult a doctor for interpretation.
           </p>
        </div>

        <button 
          onClick={() => navigate("/analytics")}
          className="w-full bg-blue-600 text-white font-bold py-4 rounded-xl shadow-lg shadow-blue-200 dark:shadow-blue-900/30 hover:scale-[1.02] transition-transform"
        >
          Add to Timeline
        </button>
      </div>
      </div>
    </div>
  );
}
